server:
  port: 8100

spring:
  application:
    name: construction-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    #    url: jdbc:postgresql://postgres-db:5432/auth_db
    #    username: admin
    #    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true